### ISSUE TITLE
Additional Instructions

### ISSUE THREAD

**Issue by mrmookie** [lukasz-brzostek/corner-popup#1]
Thank you for this project!

I'm not much of a dev and need some help:

Using the following in the script:
link1: https://example.com

How can I make it open to a new tab? 

I know for the most part, editing the content is just basic css work but a few more examples would be super helpful.

Also, using variant 10 for example:
'Your own html here' - Where do I put my html and how should it be formatted in the script?

edit: I used variant 10 and the 'content:' tag and put my html into that.

Thanks

**Comment by lukasz-brzostek** [comment]
Hello,
Nice to hear that you like my project.

There is no such option for now to set link to open in new tab, but there is one solution for this. You could insert something like: 

`link1: 'https://espritdesign.pl" target="_blank',`

This should do the trick:)
Maybe I will add new tab option in future version.
