### ISSUE TITLE
Popup CTA links do not work on Safari

### ISSUE THREAD

**Issue by katysovas** [lukasz-brzostek/corner-popup#2]
**Describe the bug**
The CTAs on the popup on Safari do not work after clicking the button. I tried using your examples as well with no luck: https://espritdesign.pl/corner-popup/demo/ 

**To Reproduce**
1. https://espritdesign.pl/corner-popup/demo/  (your demo)
2. Select Standard popup
3. Click on More button
4. A user doesn't get redirected to a new page

**Expected behavior**
It should redirect to the link specified in JS options 'link1|link2 etc'

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac (both mobile and desktop)
 - Browser: Safari
 - Version: 14

**Comment by lukasz-brzostek** [comment]
Hi,
Thanks for reporting.
This bug was related only with Safari and in new version which 
I uploaded now it shouldn't appear.

**Comment by katysovas** [comment]
Thanks for addressing it, looks good now!
