### ISSUE TITLE
Remember close action

### ISSUE THREAD

**Issue by neerbappoo** [lukasz-brzostek/corner-popup#3]
Hello

The popup is being fired on each page load.
Is there anyway for the pop to remember to close action ? something like a cookie ?
I am using variant 10.

Thanks

**Comment by lukasz-brzostek** [comment]
Hello,
There is no option in plugin to remember it was fired,
but you can achieve this using plugin API and local/session 
storage to save and read this information. 
You could use event - onBtnClick to save information that
popup was fired once, and create checking function that
will run script or not, loading information from storage:
https://javascript.info/localstorage

**Comment by lukasz-brzostek** [comment]
I'm closing this issue due to that there is currently possible to display the popup 
only once - there is new option displayOnce.
