### ISSUE TITLE
Popup event onBtnClick do not fire when the close button is clicked if variant is 4

### ISSUE THREAD

**Issue by bipsdevs** [lukasz-brzostek/corner-popup#4]
The popup event "onBtnClick" does not fire when the variant is 4. 
I am trying to fire the said event when someone clicks the popup close button. I have not added any other button in the body

**Comment by lukasz-brzostek** [comment]
Hi,

"onBtnClick" is implemented to trigger an action when someone clicks on the button inside the popup (there is one in several variants), not the close button.

If you want to do some action on close then there is "afterPopup" event - works after closing the pop-up window :)

**Comment by bipsdevs** [comment]
> Hi,
> 
> "onBtnClick" is implemented to trigger an action when someone clicks on the button inside the popup (there is one in several variants), not the close button.
> 
> If you want to do some action on close then there is "afterPopup" event - works after closing the pop-up window :)

Actually, I am using setInterval() and setTimeout(). The popup appears every 30 seconds and auto close after 10 seconds. The popup displays our recent sales to the visitor for e.g "Someone from London just purchased this item 1 hr ago". Now I want that if a visitor clicks the close button (that means he is not interested in the popup) then it will fire an event that will clear the setInterval i.e. clearInterval(). 

The "afterPopup" event as you suggested fires every time the popup close. As I said above I am using setTimeout() to auto close the popup after 10 secs so I will not want the "afterPopup" to clear the setInterval. I want an event that will fire only after the close button is clicked. Hope I am clear about what I mean to say.
If this feature is not there then I would be happy if you take the time and release an update :-)

**Comment by lukasz-brzostek** [comment]
Thread closed due to addition of new event - onCloseBtnClick
